"""Elmer adapter MVP: OpticalSpec -> .sif solver input scaffold."""

from __future__ import annotations

from pathlib import Path

from optical_spec_agent.adapters.base import AdapterReadiness, AdapterResult, BaseAdapter
from optical_spec_agent.adapters.utils import as_lower, get_status_value, list_material_names
from optical_spec_agent.models.spec import OpticalSpec


class ElmerAdapter(BaseAdapter):
    """Generate an Elmer Solver Input File scaffold."""

    tool_name = "elmer"
    display_name = "Elmer FEM"
    solver_family = "FEM"
    output_language = "sif"
    output_extension = ".sif"
    supported_solver_methods = ["fem", "electromagnetic_fem", "scattering_fem"]
    supported_physical_systems = ["waveguide", "scattering", "generic_electromagnetic_fem"]
    current_status = "mvp"
    limitations = [
        "Preview scaffold only; does not run ElmerSolver.",
        "Requires a real mesh directory/file prepared outside this adapter.",
        "Equation and boundary sections are placeholders pending richer FEM schema.",
    ]
    _consumes = [
        "physics.physical_system",
        "geometry_material.material_system",
        "simulation.solver_method",
        "simulation.software_tool",
        "simulation.boundary_condition",
        "simulation.monitor_setting",
        "output.output_observables",
    ]

    def can_handle(self, spec: OpticalSpec) -> bool:
        software = as_lower(get_status_value(spec, "simulation.software_tool"))
        solver = as_lower(get_status_value(spec, "simulation.solver_method"))
        return software == "elmer" or solver in {"fem", "electromagnetic_fem", "scattering_fem"}

    def validate_ready(self, spec: OpticalSpec, **kwargs) -> AdapterReadiness:
        mesh_path = kwargs.get("mesh_path")
        warnings: list[str] = []
        missing_required: list[str] = []
        if not self.can_handle(spec):
            warnings.append("Spec does not explicitly target Elmer/FEM; generating forced scaffold.")
        if not mesh_path:
            missing_required.append("mesh")
            warnings.append("No mesh path supplied; pass --mesh for a usable Elmer case scaffold.")
        return AdapterReadiness(
            adapter_ready=True,
            warnings=warnings,
            missing_required=missing_required,
        )

    def generate(self, spec: OpticalSpec, *, mesh_path: str | Path | None = None) -> AdapterResult:
        readiness = self.validate_ready(spec, mesh_path=mesh_path)
        materials = list_material_names(spec)
        observables = get_status_value(spec, "output.output_observables") or []
        mesh_ref = str(mesh_path) if mesh_path else "MESH_PATH_NOT_PROVIDED"

        content = f'''\
! Auto-generated by optical-spec-agent
! Adapter: Elmer MVP preview
! This SIF is a scaffold, not a production-ready electromagnetic model.
! Mesh path: {mesh_ref}
! Materials mentioned: {", ".join(materials) if materials else "not specified"}
! Output observables: {observables}
! Missing required fields: {", ".join(readiness.missing_required) if readiness.missing_required else "none"}
! Warnings:
{_comment_bullets(readiness.warnings)}

Header
  CHECK KEYWORDS Warn
  Mesh DB "." "{mesh_ref}"
End

Simulation
  Coordinate System = Cartesian
  Simulation Type = Steady State
  Steady State Max Iterations = 1
  Output Intervals = 1
  Solver Input File = case.sif
End

Constants
  Permittivity Of Vacuum = 8.8541878128e-12
  Permeability Of Vacuum = 1.25663706212e-6
End

Body 1
  Target Bodies(1) = 1
  Name = "Optical domain"
  Equation = 1
  Material = 1
End

Material 1
  Name = "Placeholder optical material"
  Relative Permittivity = 2.25
End

Equation 1
  Name = "Frequency-domain electromagnetic scaffold"
  Active Solvers(1) = 1
End

Solver 1
  Equation = "Vector Helmholtz scaffold"
  Procedure = "VectorHelmholtz" "VectorHelmholtzSolver"
  Variable = -dofs 2 E[E re:1 E im:1]
  Linear System Solver = Iterative
  Linear System Iterative Method = BiCGStab
  Linear System Max Iterations = 500
  Linear System Convergence Tolerance = 1.0e-8
End

Boundary Condition 1
  Name = "Placeholder boundary"
  Target Boundaries(1) = 1
  ! TODO: Replace with ports, scattering boundary, PML, or mode constraints.
End
'''
        return AdapterResult(
            tool=self.tool_name,
            content=content,
            language=self.output_language,
            missing_required=readiness.missing_required,
            metadata=self.metadata().model_dump(),
            warnings=readiness.warnings,
            limitations=self.limitations,
        )


def _comment_bullets(items: list[str]) -> str:
    if not items:
        return "!   - none"
    return "\n".join(f"!   - {item}" for item in items)
