"""Gmsh adapter MVP: OpticalSpec -> annotated .geo scaffold."""

from __future__ import annotations

from optical_spec_agent.adapters.base import AdapterReadiness, AdapterResult, BaseAdapter
from optical_spec_agent.adapters.utils import as_lower, get_status_value, list_material_names
from optical_spec_agent.models.spec import OpticalSpec


class GmshAdapter(BaseAdapter):
    """Generate a conservative Gmsh .geo scaffold."""

    tool_name = "gmsh"
    display_name = "Gmsh geometry / meshing"
    solver_family = "geometry / mesh"
    output_language = "geo"
    output_extension = ".geo"
    supported_solver_methods = ["mesh", "geometry", "fem", "scattering_fem"]
    supported_physical_systems = [
        "waveguide",
        "nanoparticle",
        "nanoparticle_on_film",
        "generic_2d",
        "generic_3d",
    ]
    current_status = "mvp"
    limitations = [
        "Preview scaffold only; does not run gmsh.",
        "Geometry is schematic unless OpticalSpec contains explicit geometry dimensions.",
        "Physical groups are placeholders for downstream FEM workflows.",
    ]
    _consumes = [
        "physics.physical_system",
        "physics.structure_type",
        "geometry_material.geometry_definition",
        "geometry_material.material_system",
        "geometry_material.substrate_or_film_info",
        "geometry_material.particle_info",
        "simulation.mesh_setting",
    ]

    def can_handle(self, spec: OpticalSpec) -> bool:
        software = as_lower(get_status_value(spec, "simulation.software_tool"))
        solver = as_lower(get_status_value(spec, "simulation.solver_method"))
        physical_system = as_lower(get_status_value(spec, "physics.physical_system"))
        return (
            software == "gmsh"
            or solver in {"mesh", "geometry", "fem", "scattering_fem"}
            or physical_system in {"generic_2d", "generic_3d"}
        )

    def validate_ready(self, spec: OpticalSpec, **kwargs) -> AdapterReadiness:
        warnings: list[str] = []
        missing_required: list[str] = []
        if not self.can_handle(spec):
            warnings.append("Spec does not explicitly target Gmsh; generating forced preview scaffold.")

        geometry = get_status_value(spec, "geometry_material.geometry_definition")
        geometry_type = getattr(geometry, "geometry_type", None) if geometry else None
        dimensions = getattr(geometry, "dimensions", {}) if geometry else {}
        if geometry is None or (not geometry_type and not dimensions):
            missing_required.append("geometry_material.geometry_definition")
            warnings.append("Missing geometry_definition; .geo will be an annotated placeholder.")

        return AdapterReadiness(
            adapter_ready=True,
            warnings=warnings,
            missing_required=missing_required,
        )

    def generate(self, spec: OpticalSpec) -> AdapterResult:
        readiness = self.validate_ready(spec)
        physical_system = as_lower(get_status_value(spec, "physics.physical_system"))
        structure_type = get_status_value(spec, "physics.structure_type") or "unknown"
        materials = list_material_names(spec)
        geometry_comment = _geometry_comment(spec)
        geometry_block = _geometry_block_for(physical_system)

        content = f'''\
// Auto-generated by optical-spec-agent
// Adapter: Gmsh MVP preview
// This .geo file is an annotated scaffold. It is not production-ready geometry.
// Physical system: {physical_system or "unknown"}
// Structure type: {structure_type}
// Materials mentioned: {", ".join(materials) if materials else "not specified"}
// Geometry hints: {geometry_comment}
// Missing required fields: {", ".join(readiness.missing_required) if readiness.missing_required else "none"}
// Warnings:
{_comment_bullets(readiness.warnings)}

SetFactory("OpenCASCADE");

lc = 0.05; // characteristic length in model units; review before meshing
Mesh.CharacteristicLengthMin = lc / 2;
Mesh.CharacteristicLengthMax = lc;

{geometry_block}

// Placeholder physical groups for downstream FEM tools.
Physical Volume("domain") = {{1}};
Physical Surface("boundaries") = Boundary{{ Volume{{1}}; }};
'''
        return AdapterResult(
            tool=self.tool_name,
            content=content,
            language=self.output_language,
            missing_required=readiness.missing_required,
            metadata=self.metadata().model_dump(),
            warnings=readiness.warnings,
            limitations=self.limitations,
        )


def _geometry_comment(spec: OpticalSpec) -> str:
    geom = get_status_value(spec, "geometry_material.geometry_definition")
    if geom is None:
        return "missing geometry_definition"
    description = getattr(geom, "description", "") or ""
    dimensions = getattr(geom, "dimensions", {}) or {}
    return f"{description[:120]} dimensions={dimensions}"


def _geometry_block_for(physical_system: str) -> str:
    if physical_system == "nanoparticle_on_film":
        return """\n// Representative nanoparticle-on-film scaffold, not exact CAD.\n// Film box plus sphere; gap is documented but not boolean-subtracted.\nBox(1) = {-0.5, -0.5, -0.10, 1.0, 1.0, 0.10}; // film\nSphere(2) = {0, 0, 0.145, 0.04}; // particle placeholder\nBooleanFragments{ Volume{1}; Delete; }{ Volume{2}; Delete; }\nPhysical Volume(\"film\") = {1};\nPhysical Volume(\"particle\") = {2};\n"""
    if physical_system == "waveguide":
        return """\n// Representative waveguide cross-section scaffold.\nRectangle(1) = {-0.4, -0.2, 0, 0.8, 0.4, 0};\nExtrude {0, 0, 1.0} { Surface{1}; Layers{1}; Recombine; }\nPhysical Surface(\"waveguide_cross_section\") = {1};\n"""
    return """\n// Generic 3D placeholder domain.\nBox(1) = {-0.5, -0.5, -0.5, 1.0, 1.0, 1.0};\n"""


def _comment_bullets(items: list[str]) -> str:
    if not items:
        return "//   - none"
    return "\n".join(f"//   - {item}" for item in items)
