"""Documentation index checks."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_docs_index_exists_and_links_major_docs():
    index = ROOT / "docs" / "README.md"
    assert index.exists()
    text = index.read_text(encoding="utf-8")
    required = [
        "Current public prerelease: v0.9.0rc5",
        "Current main development version: `0.9.0rc6.dev0`",
        "release_readiness_current.md",
        "release_readiness_v0.9.0rc6.md",
        "v1_0_gap_audit.md",
        "rc6_development_plan.md",
        "v1_0_decision_matrix.md",
        "github_release_draft_v0.9.0rc5.md",
        "release_notes_v0.9.0rc5.md",
        "post_release_status_v0.9.0rc5.md",
        "quality_gates.md",
        "ci_quality_gate_parity.md",
        "release_dry_run_operations.md",
        "packaging_gate.md",
        "testpypi_dry_run_gate.md",
        "pypi_publication_decision.md",
        "pypi_publication_readiness_checklist.md",
        "pypi_post_publication_verification_plan.md",
        "publication_decision_record.md",
        "testpypi_upload_approval_v0.9.0rc6.dev0.md",
        "testpypi_upload_attempt_v0.9.0rc6.dev0.md",
        "testpypi_status_v0.9.0rc6.dev0.md",
        "testpypi_trusted_publishing.md",
        "secrets_and_token_hygiene.md",
        "cli_contract.md",
        "schema_contract.md",
        "schema_compatibility_policy.md",
        "v1_0_compatibility_policy.md",
        "v1_0_public_contract_freeze.md",
        "v1_0_public_contract_freeze_checklist.md",
        "public_contract_change_checklist.md",
        "public_contract_manifest.json",
        "validation_gate.md",
        "validation_boundary.md",
        "validation_evidence_manifest.md",
        "adapter_maturity_model.md",
        "open_source_solver_validation_plan.md",
        "open_solver_validation_harness.md",
        "gmsh_optional_validation_pilot.md",
        "gmsh_level3_readiness.md",
        "meep_optional_validation_pilot.md",
        "meep_level3_readiness.md",
        "mpb_optional_validation_pilot.md",
        "mpb_level3_readiness.md",
        "optiland_optional_validation_pilot.md",
        "optiland_level3_readiness.md",
        "elmer_optional_validation_pilot.md",
        "elmer_level3_readiness.md",
        "manual_solver_validation_report_template.md",
        "manual_solver_validation_reports/gmsh_validation_pilot_template.md",
        "manual_solver_validation_reports/meep_validation_report_schema.json",
        "manual_solver_validation_reports/mpb_validation_report_schema.json",
        "manual_solver_validation_reports/optiland_validation_report_schema.json",
        "manual_solver_validation_reports/elmer_validation_report_schema.json",
        "../validation/gmsh/gmsh_validation_pilot_2026-05-14.md",
        "../validation/meep/meep_validation_pilot_2026-05-14.md",
        "../validation/mpb/mpb_validation_pilot_2026-05-14.md",
        "../validation/optiland/optiland_validation_pilot_2026-05-14.md",
        "../validation/elmer/README.md",
        "../validation/elmer/elmer_install_deferred_2026-05-15.md",
        "pytest_marker_policy.md",
        "offline_user_journey.md",
        "error_model.md",
        "migration_notes_pre_v1.md",
        "open_source_solver_strategy.md",
        "proprietary_solver_policy.md",
        "external_solver_policy.md",
        "external_llm_policy.md",
        "../examples/README.md",
        "../examples/e2e/README.md",
        "../examples/examples_manifest.json",
        "maintainer_decision_log.md",
        "maintainer_operations_checklist.md",
        "v1_0_readiness_scorecard.md",
        "v1_0_gap_audit.md",
        "rc6_development_plan.md",
        "v1_0_decision_matrix.md",
        "v1_0_public_contract_freeze_checklist.md",
        "publication_decision_record.md",
    ]
    for phrase in required:
        assert phrase in text
