"""Starter material records for local optical design previews."""

from __future__ import annotations

from .models import MaterialDetail, RefractiveIndexModel


PREVIEW_SOURCE_NOTE = (
    "Curated local preview value for examples only; verify against a trusted "
    "material database or measurement before drawing physical conclusions."
)


MATERIALS: tuple[MaterialDetail, ...] = (
    MaterialDetail(
        material_id="air",
        display_name="Air",
        aliases=["vacuum", "background"],
        category="ambient",
        common_use=["background medium", "ray optics"],
        optical_role="ambient reference medium",
        wavelength_range_nm=(400, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=1.0, k=0.0, wavelength_nm=589),
        notes=["Useful as a local preview background medium."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="water",
        display_name="Water",
        aliases=["h2o"],
        category="liquid",
        common_use=["biosensing", "nanoparticle environment"],
        optical_role="dielectric surrounding medium",
        wavelength_range_nm=(400, 900),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=1.33, k=0.0, wavelength_nm=589),
        notes=["Approximate visible-wavelength preview value."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="sio2",
        display_name="Silicon dioxide (SiO2)",
        aliases=["silica", "oxide", "fused_silica"],
        category="dielectric",
        common_use=["thin film coating", "waveguide cladding", "spacer"],
        optical_role="low-index dielectric",
        wavelength_range_nm=(400, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=1.45, k=0.0, wavelength_nm=633),
        notes=["Approximate preview constant; use wavelength-dependent data for real design."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="si",
        display_name="Silicon (Si)",
        aliases=["silicon"],
        category="semiconductor",
        common_use=["waveguide", "photonic crystal", "metasurface"],
        optical_role="high-index semiconductor",
        wavelength_range_nm=(1100, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=3.48, k=0.0, wavelength_nm=1550),
        notes=["Telecom preview value; visible absorption is not represented by this placeholder."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="si3n4",
        display_name="Silicon nitride (Si3N4)",
        aliases=["sin", "silicon_nitride"],
        category="dielectric",
        common_use=["waveguide", "metasurface"],
        optical_role="medium-index dielectric",
        wavelength_range_nm=(500, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=2.0, k=0.0, wavelength_nm=633),
        notes=["Approximate preview value; deposition process can change optical constants."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="tio2",
        display_name="Titanium dioxide (TiO2)",
        aliases=["titania"],
        category="dielectric",
        common_use=["thin film coating", "dielectric metasurface"],
        optical_role="high-index dielectric",
        wavelength_range_nm=(450, 900),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=2.4, k=0.0, wavelength_nm=633),
        notes=["Approximate preview value; phase and process dependence are not modeled."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="al2o3",
        display_name="Aluminum oxide (Al2O3)",
        aliases=["alumina"],
        category="dielectric",
        common_use=["thin film coating", "spacer", "passivation"],
        optical_role="medium-index dielectric",
        wavelength_range_nm=(400, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=1.76, k=0.0, wavelength_nm=633),
        notes=["Approximate local preview value."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="au",
        display_name="Gold (Au)",
        aliases=["gold"],
        category="metal",
        common_use=["nanoparticle plasmonics", "film", "antenna"],
        optical_role="plasmonic metal",
        wavelength_range_nm=(400, 900),
        refractive_index_model=RefractiveIndexModel(kind="placeholder", n=0.2, k=3.4, wavelength_nm=633),
        notes=["Placeholder metal constant; use tabulated data before physical interpretation."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="ag",
        display_name="Silver (Ag)",
        aliases=["silver"],
        category="metal",
        common_use=["nanoparticle plasmonics", "film", "antenna"],
        optical_role="plasmonic metal",
        wavelength_range_nm=(400, 900),
        refractive_index_model=RefractiveIndexModel(kind="placeholder", n=0.14, k=3.98, wavelength_nm=633),
        notes=["Placeholder metal constant; use tabulated data before physical interpretation."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="ito",
        display_name="Indium tin oxide (ITO)",
        aliases=["indium_tin_oxide"],
        category="transparent conductor",
        common_use=["transparent electrode", "active photonics"],
        optical_role="conductive optical layer",
        wavelength_range_nm=(450, 1600),
        refractive_index_model=RefractiveIndexModel(kind="placeholder", n=1.9, k=0.02, wavelength_nm=633),
        notes=["Process-dependent preview placeholder."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="gaas",
        display_name="Gallium arsenide (GaAs)",
        aliases=["gallium_arsenide"],
        category="semiconductor",
        common_use=["photonic crystal", "waveguide", "emitter platform"],
        optical_role="high-index III-V semiconductor",
        wavelength_range_nm=(900, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=3.4, k=0.0, wavelength_nm=1550),
        notes=["Approximate infrared preview value."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="glass_bk7_preview",
        display_name="BK7 glass preview",
        aliases=["bk7", "n-bk7"],
        category="glass",
        common_use=["lens/ray optics", "substrate"],
        optical_role="optical glass preview",
        wavelength_range_nm=(400, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=1.5168, k=0.0, wavelength_nm=589),
        notes=["Preview-only lens-design helper; do not treat as a full glass catalog."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
    MaterialDetail(
        material_id="glass_fused_silica_preview",
        display_name="Fused silica glass preview",
        aliases=["fused_silica_preview", "uvfs"],
        category="glass",
        common_use=["lens/ray optics", "substrate", "window"],
        optical_role="low-dispersion glass preview",
        wavelength_range_nm=(250, 1600),
        refractive_index_model=RefractiveIndexModel(kind="constant", n=1.458, k=0.0, wavelength_nm=589),
        notes=["Preview-only glass helper; verify dispersion for real optical design."],
        source_note=PREVIEW_SOURCE_NOTE,
    ),
)
