"""MPB adapter MVP: OpticalSpec -> MPB Python preview script."""

from __future__ import annotations

from optical_spec_agent.adapters.base import AdapterReadiness, AdapterResult, BaseAdapter
from optical_spec_agent.adapters.utils import as_lower, get_status_value, list_material_names
from optical_spec_agent.models.spec import OpticalSpec


class MPBAdapter(BaseAdapter):
    """Generate a conservative MPB Python scaffold for band/mode tasks."""

    tool_name = "mpb"
    display_name = "MIT Photonic Bands (MPB)"
    solver_family = "eigenmode / band structure"
    output_language = "python"
    output_extension = ".py"
    supported_solver_methods = ["band_structure", "mode_solver", "eigenmode", "frequency_domain"]
    supported_physical_systems = ["photonic_crystal", "waveguide", "periodic_structure"]
    current_status = "mvp"
    limitations = [
        "Preview scaffold only; does not run MPB.",
        "Uses default lattice, k-points, resolution, and num_bands when missing.",
        "Geometry is intentionally schematic until OpticalSpec carries richer periodic geometry.",
    ]
    _consumes = [
        "physics.physical_system",
        "physics.structure_type",
        "geometry_material.geometry_definition",
        "geometry_material.material_system",
        "simulation.solver_method",
        "simulation.software_tool",
        "simulation.source_setting",
        "output.output_observables",
    ]

    def can_handle(self, spec: OpticalSpec) -> bool:
        software = as_lower(get_status_value(spec, "simulation.software_tool"))
        solver = as_lower(get_status_value(spec, "simulation.solver_method"))
        physical_system = as_lower(get_status_value(spec, "physics.physical_system"))
        return (
            software == "mpb"
            or solver in {"band_structure", "band_diagram", "mode_solver", "eigenmode", "frequency_domain"}
            or physical_system in {"photonic_crystal", "periodic_structure"}
        )

    def validate_ready(self, spec: OpticalSpec, **kwargs) -> AdapterReadiness:
        warnings: list[str] = []
        defaults: list[str] = []
        if not self.can_handle(spec):
            warnings.append("Spec does not explicitly target MPB; generating forced preview scaffold.")

        geometry = get_status_value(spec, "geometry_material.geometry_definition")
        if geometry is None:
            warnings.append("Missing geometry_definition; MPB scaffold will use a default dielectric block.")
            defaults.append("geometry: default dielectric block in a unit lattice")

        defaults.extend([
            "lattice: mp.Lattice(size=mp.Vector3(1, 1))",
            "k_points: Gamma-X-M-Gamma path",
            "num_bands: 8",
            "resolution: 32",
        ])
        return AdapterReadiness(
            adapter_ready=True,
            warnings=warnings,
            defaults_applied=defaults,
        )

    def generate(self, spec: OpticalSpec) -> AdapterResult:
        readiness = self.validate_ready(spec)
        physical_system = get_status_value(spec, "physics.physical_system") or "unknown"
        structure_type = get_status_value(spec, "physics.structure_type") or "unknown"
        materials = list_material_names(spec) or ["Si", "Air"]
        source_setting = get_status_value(spec, "simulation.source_setting")
        wavelength = getattr(source_setting, "wavelength_range", "") if source_setting else ""

        script = f'''\
"""
Auto-generated by optical-spec-agent
Adapter: MPB MVP preview

This script is a scaffold for MPB band/mode analysis. It does not run inside
optical-spec-agent and it is not production-grade. Review lattice, geometry,
k-points, material models, resolution, and units before using it for research.

Physical system: {physical_system}
Structure type: {structure_type}
Materials mentioned: {", ".join(materials)}
Wavelength hint: {wavelength or "not specified"}

Defaults / placeholders:
{_format_bullets(readiness.defaults_applied)}

Warnings:
{_format_bullets(readiness.warnings, empty="  - none")}
"""

import meep as mp
from meep import mpb


resolution = 32
num_bands = 8

# Default unit-cell lattice. Replace with confirmed lattice constants when available.
geometry_lattice = mp.Lattice(size=mp.Vector3(1, 1))

# Schematic geometry only. OpticalSpec does not yet carry full periodic geometry.
geometry = [
    mp.Block(
        center=mp.Vector3(),
        size=mp.Vector3(0.4, 0.4, mp.inf),
        material=mp.Medium(epsilon=12.0),
    )
]

# Gamma-X-M-Gamma path with interpolation.
k_points = [
    mp.Vector3(0, 0),
    mp.Vector3(0.5, 0),
    mp.Vector3(0.5, 0.5),
    mp.Vector3(0, 0),
]
k_points = mp.interpolate(4, k_points)

ms = mpb.ModeSolver(
    geometry_lattice=geometry_lattice,
    geometry=geometry,
    k_points=k_points,
    resolution=resolution,
    num_bands=num_bands,
)

# Choose run_te/run_tm/run depending on polarization and dimensionality.
ms.run()
print("MPB preview complete. Inspect ms.all_freqs for band frequencies.")
'''
        metadata = self.metadata().model_dump()
        return AdapterResult(
            tool=self.tool_name,
            content=script,
            language=self.output_language,
            metadata=metadata,
            warnings=readiness.warnings,
            defaults_applied=readiness.defaults_applied,
            limitations=self.limitations,
        )


def _format_bullets(items: list[str], *, empty: str = "  - none") -> str:
    if not items:
        return empty
    return "\n".join(f"  - {item}" for item in items)
