"""Optiland adapter MVP: OpticalSpec -> Python ray-tracing scaffold."""

from __future__ import annotations

from optical_spec_agent.adapters.base import AdapterReadiness, AdapterResult, BaseAdapter
from optical_spec_agent.adapters.utils import as_lower, get_status_value
from optical_spec_agent.models.spec import OpticalSpec


class OptilandAdapter(BaseAdapter):
    """Generate an honest Optiland scaffold for imaging optics tasks."""

    tool_name = "optiland"
    display_name = "Optiland"
    solver_family = "sequential ray tracing"
    output_language = "python"
    output_extension = ".py"
    supported_solver_methods = ["ray_trace", "raytracing", "geometric_optics"]
    supported_physical_systems = ["lens", "imaging_system", "optical_system", "ray_tracing"]
    current_status = "mvp"
    limitations = [
        "Scaffold only; does not run Optiland.",
        "Current OpticalSpec lacks a full lens surface sequence and glass catalog mapping.",
        "Generated code must be completed by an optical designer before optimization.",
    ]
    _consumes = [
        "physics.physical_system",
        "geometry_material.geometry_definition",
        "simulation.solver_method",
        "simulation.software_tool",
        "simulation.source_setting",
        "output.output_observables",
        "output.postprocess_target",
    ]

    def can_handle(self, spec: OpticalSpec) -> bool:
        software = as_lower(get_status_value(spec, "simulation.software_tool"))
        solver = as_lower(get_status_value(spec, "simulation.solver_method"))
        physical_system = as_lower(get_status_value(spec, "physics.physical_system"))
        return (
            software == "optiland"
            or solver in {"ray_trace", "raytracing", "geometric_optics"}
            or physical_system in {"lens", "imaging_system", "optical_system", "ray_tracing"}
        )

    def validate_ready(self, spec: OpticalSpec, **kwargs) -> AdapterReadiness:
        warnings: list[str] = []
        missing_required = [
            "geometry_material.geometry_definition.lens_surface_sequence",
            "geometry_material.material_system.glass_catalog",
            "simulation.source_setting.fields",
        ]
        if not self.can_handle(spec):
            warnings.append("Spec does not explicitly target Optiland; generating forced scaffold.")
        warnings.append("Optiland MVP is scaffold-level because lens surfaces are not represented yet.")
        return AdapterReadiness(
            adapter_ready=True,
            warnings=warnings,
            missing_required=missing_required,
        )

    def generate(self, spec: OpticalSpec) -> AdapterResult:
        readiness = self.validate_ready(spec)
        source_setting = get_status_value(spec, "simulation.source_setting")
        wavelength_hint = getattr(source_setting, "wavelength_range", "") if source_setting else ""
        observables = get_status_value(spec, "output.output_observables") or []

        content = f'''\
"""
Auto-generated by optical-spec-agent
Adapter: Optiland MVP scaffold

This is not a completed lens design. Current OpticalSpec does not yet carry a
full lens-surface sequence, glass catalog selection, field definitions, stop
surface, or optimization operands. Treat this file as a starting checklist.

Wavelength hint: {wavelength_hint or "not specified"}
Requested observables: {observables}
Missing required design data:
{_format_bullets(readiness.missing_required)}
"""

try:
    import optiland  # type: ignore
except ImportError:
    optiland = None


def build_optical_system():
    """Build a placeholder optical system once real lens data is supplied."""
    if optiland is None:
        raise RuntimeError(
            "Optiland is not installed. Install it separately before running this scaffold."
        )

    # TODO: Replace this with concrete Optiland API calls for:
    # - sequential surfaces
    # - curvature / thickness / semi-diameter
    # - glass catalog entries
    # - aperture stop
    # - fields and wavelengths
    optical_system = None
    return optical_system


def main():
    system = build_optical_system()
    # TODO: Evaluate spot diagram, MTF, and aberrations after completing system.
    print("Optiland scaffold created; complete TODOs before execution.", system)


if __name__ == "__main__":
    main()
'''
        return AdapterResult(
            tool=self.tool_name,
            content=content,
            language=self.output_language,
            missing_required=readiness.missing_required,
            metadata=self.metadata().model_dump(),
            warnings=readiness.warnings,
            limitations=self.limitations,
        )


def _format_bullets(items: list[str]) -> str:
    if not items:
        return "  - none"
    return "\n".join(f"  - {item}" for item in items)
