"""Meep Python script template — nanoparticle_on_film + plane_wave + scattering_spectrum.

Renders a MeepInputModel into a runnable Python script string.
"""

from __future__ import annotations

from .models import MeepInputModel


def render_script(m: MeepInputModel) -> str:
    """Render a MeepInputModel into a Python script."""

    # --- Sweep logic ---
    has_sweep = m.sweep_variable and m.sweep_start_um is not None and m.sweep_end_um is not None
    if has_sweep:
        loop_header, loop_footer = _sweep_loop(m)
    else:
        loop_header = ""
        loop_footer = ""

    # --- Postprocess imports ---
    pp_extra = ""
    if m.postprocess:
        pp_extra = "from scipy.signal import find_peaks\n"

    # --- Material definitions ---
    mat_defs = _material_defs(m)

    # --- Geometry block ---
    geom_block = _geometry_block(m)

    # --- Postprocess block ---
    pp_block = _postprocess_block(m)

    script = f'''\
"""
Meep FDTD simulation — auto-generated by optical-spec-agent (Meep adapter v0.1).

Physical system: nanoparticle_on_film
  particle: {m.particle_material} {m.particle_shape}, radius={m.particle_radius_um * 1000:.1f}nm
  film:     {m.film_material}, thickness={m.film_thickness_um * 1000:.1f}nm
  gap:      n={m.gap_medium_n}, thickness={m.gap_thickness_um * 1000:.1f}nm
  source:   plane wave, {m.wavelength_min_um * 1000:.0f}-{m.wavelength_max_um * 1000:.0f}nm

NOTE: Material model is SIMPLIFIED (single-Drude). For production use, replace
      with full Johnson-Christy or Lorentz-Drude fit data.
"""

import meep as mp
import numpy as np
import matplotlib.pyplot as plt
{pp_extra}

# =====================================================================
# Materials (simplified single-Drude model)
# =====================================================================
{mat_defs}
gap_medium = mp.Medium(epsilon={m.gap_medium_n ** 2:.4f})

# =====================================================================
# Simulation parameters
# =====================================================================
resolution = {m.resolution}  # pixels/μm
pml_um = {m.pml_thickness_um}
fcen = {(1.0 / ((m.wavelength_min_um + m.wavelength_max_um) / 2.0)):.4f}  # center frequency (1/μm)
df = {(1.0 / m.wavelength_min_um - 1.0 / m.wavelength_max_um):.4f}  # frequency width (1/μm)
nfreq = {m.freq_points}

# =====================================================================
# Geometry & cell
# =====================================================================
{geom_block}

# =====================================================================
# Source: plane wave
# =====================================================================
sources = [mp.Source(
    src=mp.GaussianSource(fcen, fwidth=df),
    component=mp.Ez,
    center=mp.Vector3(0, 0, {m.film_thickness_um + m.particle_radius_um * 2 + m.pml_thickness_um + 0.5:.2f}),
    size=mp.Vector3(sx, sy),
)]

# =====================================================================
# Simulation
# =====================================================================
sim = mp.Simulation(
    cell_size=cell,
    geometry=geometry,
    sources=sources,
    boundary_layers=[mp.PML(pml_um)],
    default_material=gap_medium,
    resolution=resolution,
)

# Flux monitor boxes for scattering cross-section
# (simplified: one box around the particle)
box_zcen = film_thickness + gap + r_particle
flux_box = sim.add_flux(
    fcen, df, nfreq,
    mp.FluxRegion(center=mp.Vector3(0, 0, box_zcen + r_particle + 0.05), size=mp.Vector3(2*r_particle + 0.1, 2*r_particle + 0.1, 0)),
)

{loop_header}
sim.run(until=200)  # simplified: fixed time steps. Adjust based on your needs.
{loop_footer}

# =====================================================================
# Post-processing: spectrum
# =====================================================================
freqs = mp.get_flux_freqs(flux_box)
flux = mp.get_fluxes(flux_box)
wl_um = np.array(1.0 / np.array(freqs))  # wavelength in μm
wl_nm = wl_um * 1000

plt.figure(figsize=(8, 5))
plt.plot(wl_nm, flux, "b-")
plt.xlabel("Wavelength (nm)")
plt.ylabel("Flux (arb. units)")
plt.title("Scattering flux — {m.particle_material} {m.particle_shape} on {m.film_material} film")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("scattering_spectrum.png", dpi=150)
plt.show()
print("Spectrum saved to scattering_spectrum.png")

{pp_block}
'''
    return script


def _material_defs(m: MeepInputModel) -> str:
    """Generate simplified Drude material definitions."""
    defs = []
    for label, mat in [("particle_mat", m.particle_material), ("film_mat", m.film_material)]:
        if mat in ("Au", "au"):
            defs.append(
                f'# Simplified Drude model for Au (placeholder for Johnson-Christy data)\n'
                f'{label} = mp.Drude(epsilon=1.0, plasma_freq=1.37e16, gamma=4.08e13)\n'
                f'# In Meep units: ω_p = 9.03 eV, γ = 0.071 eV → converted to 1/μm\n'
                f'# For production: use mp.Medium(epsilon=...) with tabulated n(ω), k(ω)'
            )
        elif mat in ("Ag", "ag"):
            defs.append(
                f'# Simplified Drude model for Ag (placeholder)\n'
                f'{label} = mp.Drude(epsilon=1.0, plasma_freq=1.37e16, gamma=2.73e13)\n'
                f'# For production: use full Lorentz-Drude or tabulated data'
            )
        else:
            defs.append(f'{label} = mp.Medium(epsilon=1.0)  # placeholder for {mat}')
    return "\n".join(defs)


def _geometry_block(m: MeepInputModel) -> str:
    """Generate geometry and cell setup code."""
    if m.particle_shape == "sphere":
        particle_geom = (
            "mp.Sphere(material=particle_mat,\n"
            f"           center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            f"           radius=r_particle)"
        )
    elif m.particle_shape == "cube":
        particle_geom = (
            "mp.Block(material=particle_mat,\n"
            f"         center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            f"         size=mp.Vector3(2*r_particle, 2*r_particle, 2*r_particle))"
        )
    elif m.particle_shape == "cylinder":
        particle_geom = (
            "mp.Cylinder(material=particle_mat,\n"
            f"             center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            f"             radius=r_particle, height=2*r_particle)"
        )
    else:
        particle_geom = f"mp.Sphere(material=particle_mat, center=mp.Vector3(0, 0, film_thickness + gap + r_particle), radius=r_particle)  # fallback"

    return f'''\
r_particle = {m.particle_radius_um:.6f}   # particle radius (μm) — from spec.particle_info
film_thickness = {m.film_thickness_um:.6f}  # film thickness (μm) — from spec.substrate_or_film_info
gap = {m.gap_thickness_um:.6f}              # gap thickness (μm) — from spec.gap_medium

# Cell size: padding around the structure
pad = r_particle + 0.5  # μm padding
sx = 2 * (r_particle + pad)
sy = sx
sz = film_thickness + gap + 2 * r_particle + 2 * pad + 2 * pml_um
cell = mp.Vector3(sx, sy, sz)

geometry = [
    # Film layer (extends in x-y)
    mp.Block(material=film_mat,
             center=mp.Vector3(0, 0, film_thickness / 2),
             size=mp.Vector3(mp.inf, mp.inf, film_thickness)),
    # Particle on top of film
    {particle_geom},
]'''


def _sweep_loop(m: MeepInputModel) -> tuple[str, str]:
    """Return (loop_header, loop_footer) for a gap sweep."""
    steps = m.sweep_steps or 11
    return (
        f'gap_values = np.linspace({m.sweep_start_um:.6f}, {m.sweep_end_um:.6f}, {steps})\n'
        f'print(f"Sweeping gap from {{gap_values[0]*1000:.1f}} to {{gap_values[-1]*1000:.1f}} nm in {{len(gap_values)}} steps")\n'
        f'all_flux = []\n'
        f'for i, g in enumerate(gap_values):\n'
        f'    print(f"  Step {{i+1}}/{{len(gap_values)}}: gap = {{g*1000:.1f}} nm")\n'
        f'    gap = g\n'
        f'    # Rebuild geometry with new gap\n'
        f'    geometry = [\n'
        f'        mp.Block(material=film_mat, center=mp.Vector3(0, 0, film_thickness / 2), size=mp.Vector3(mp.inf, mp.inf, film_thickness)),\n'
        f'        mp.Sphere(material=particle_mat, center=mp.Vector3(0, 0, film_thickness + gap + r_particle), radius=r_particle),\n'
        f'    ]\n'
        f'    sim = mp.Simulation(cell_size=cell, geometry=geometry, sources=sources, boundary_layers=[mp.PML(pml_um)], default_material=gap_medium, resolution=resolution)\n'
        f'    flux_box = sim.add_flux(fcen, df, nfreq, mp.FluxRegion(center=mp.Vector3(0, 0, film_thickness + gap + r_particle + r_particle + 0.05), size=mp.Vector3(2*r_particle + 0.1, 2*r_particle + 0.1, 0)))\n',
        f'    all_flux.append(mp.get_fluxes(flux_box))\n'
        f'    sim.reset()\n'
        f'\n'
        f'flux = np.mean(all_flux, axis=0)  # simplified: average over sweep points'
    )


def _postprocess_block(m: MeepInputModel) -> str:
    """Generate post-processing code for resonance/FWHM extraction."""
    if not m.postprocess:
        return ""

    lines = ["# =====================================================================",
             "# Post-processing: resonance / FWHM extraction",
             "# ====================================================================="]

    if "resonance_wavelength" in m.postprocess:
        lines.append("""
# Find resonance peak
peaks, props = find_peaks(flux, height=max(flux) * 0.5)
if len(peaks) > 0:
    res_idx = peaks[np.argmax(props["peak_heights"])]
    res_wl = wl_nm[res_idx]
    print(f"Resonance wavelength: {res_wl:.1f} nm")
else:
    print("No clear resonance peak found")
""")

    if "fwhm_extraction" in m.postprocess:
        lines.append("""
# FWHM estimation (simplified half-max method)
if len(peaks) > 0:
    peak_flux = max(flux)
    half_max = peak_flux / 2.0
    above = np.where(np.array(flux) >= half_max)[0]
    if len(above) > 1:
        fwhm = wl_nm[above[-1]] - wl_nm[above[0]]
        print(f"FWHM: {fwhm:.1f} nm")
    else:
        print("Could not estimate FWHM")
""")

    if "T2_extraction" in m.postprocess:
        lines.append("""
# T2 (dephasing time) from FWHM: T2 = 2ℏ / Γ, where Γ = ℏω·FWHM/λ²
# Simplified: T2 ≈ 2λ² / (2πc·FWHM)
if len(peaks) > 0 and len(above) > 1:
    import scipy.constants as const
    res_wl_m = res_wl * 1e-9
    fwhm_m = fwhm * 1e-9
    T2 = 2 * res_wl_m**2 / (2 * np.pi * const.c * fwhm_m)
    print(f"T2 (dephasing time): {T2*1e15:.1f} fs")
""")

    return "\n".join(lines)
