"""Meep Python script templates for nanoparticle_on_film generation modes."""

from __future__ import annotations

from .models import MeepInputModel


def render_script(m: MeepInputModel) -> str:
    """Render a MeepInputModel into a Python script."""
    mode = getattr(m, "script_mode", "preview")
    if getattr(m, "smoke", False) or mode == "smoke":
        return _render_smoke(m)
    if mode == "research_preview":
        return _render_research_preview(m)
    return _render_preview(m)


def _render_preview(m: MeepInputModel) -> str:
    """Render the legacy preview template used by default generation."""
    has_sweep = m.sweep_variable and m.sweep_start_um is not None and m.sweep_end_um is not None
    if has_sweep:
        loop_header, loop_footer = _preview_sweep_loop(m)
    else:
        loop_header = ""
        loop_footer = ""

    pp_extra = ""
    if m.postprocess:
        pp_extra = "from scipy.signal import find_peaks\n"

    mat_defs = _preview_material_defs(m)
    geom_block = _preview_geometry_block(m)
    pp_block = _preview_postprocess_block(m)

    defaults_note = ""
    if m.defaults_applied:
        lines = ["Adapter-applied defaults (values not specified in input spec):"]
        for d in m.defaults_applied:
            lines.append(f"  - {d}")
        defaults_note = "\n" + "\n".join(lines)

    script = f'''\
"""
Meep FDTD simulation — auto-generated by optical-spec-agent (Meep adapter v0.1).

Physical system: nanoparticle_on_film
  particle: {m.particle_material} {m.particle_shape}, radius={m.particle_radius_um * 1000:.1f}nm
  film:     {m.film_material}, thickness={m.film_thickness_um * 1000:.1f}nm
  gap:      n={m.gap_medium_n}, thickness={m.gap_thickness_um * 1000:.1f}nm
  source:   plane wave, {m.wavelength_min_um * 1000:.0f}-{m.wavelength_max_um * 1000:.0f}nm

NOTE: Material model is SIMPLIFIED (single-Drude). For production use, replace
      with full Johnson-Christy or Lorentz-Drude fit data.
{defaults_note}"""

import meep as mp
import numpy as np
import matplotlib.pyplot as plt
{pp_extra}

# =====================================================================
# Materials (simplified single-Drude model)
# =====================================================================
{mat_defs}
gap_medium = mp.Medium(epsilon={m.gap_medium_n ** 2:.4f})

# =====================================================================
# Simulation parameters
# =====================================================================
resolution = {m.resolution}  # pixels/μm
pml_um = {m.pml_thickness_um}
fcen = {(1.0 / ((m.wavelength_min_um + m.wavelength_max_um) / 2.0)):.4f}  # center frequency (1/μm)
df = {(1.0 / m.wavelength_min_um - 1.0 / m.wavelength_max_um):.4f}  # frequency width (1/μm)
nfreq = {m.freq_points}

# =====================================================================
# Geometry & cell
# =====================================================================
{geom_block}

# =====================================================================
# Source: plane wave
# =====================================================================
sources = [mp.Source(
    src=mp.GaussianSource(fcen, fwidth=df),
    component=mp.Ez,
    center=mp.Vector3(0, 0, {m.film_thickness_um + m.particle_radius_um * 2 + m.pml_thickness_um + 0.5:.2f}),
    size=mp.Vector3(sx, sy),
)]

# =====================================================================
# Simulation
# =====================================================================
sim = mp.Simulation(
    cell_size=cell,
    geometry=geometry,
    sources=sources,
    boundary_layers=[mp.PML(pml_um)],
    default_material=gap_medium,
    resolution=resolution,
)

# Flux monitor boxes for scattering cross-section
# (simplified: one box around the particle)
box_zcen = film_thickness + gap + r_particle
flux_box = sim.add_flux(
    fcen, df, nfreq,
    mp.FluxRegion(center=mp.Vector3(0, 0, box_zcen + r_particle + 0.05), size=mp.Vector3(2*r_particle + 0.1, 2*r_particle + 0.1, 0)),
)

{loop_header}
sim.run(until=200)  # simplified: fixed time steps. Adjust based on your needs.
{loop_footer}

# =====================================================================
# Post-processing: spectrum
# =====================================================================
freqs = mp.get_flux_freqs(flux_box)
flux = mp.get_fluxes(flux_box)
wl_um = np.array(1.0 / np.array(freqs))  # wavelength in μm
wl_nm = wl_um * 1000

plt.figure(figsize=(8, 5))
plt.plot(wl_nm, flux, "b-")
plt.xlabel("Wavelength (nm)")
plt.ylabel("Flux (arb. units)")
plt.title("Scattering flux — {m.particle_material} {m.particle_shape} on {m.film_material} film")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("scattering_spectrum.png", dpi=150)
plt.show()
print("Spectrum saved to scattering_spectrum.png")

{pp_block}
'''
    return script


def _render_research_preview(m: MeepInputModel) -> str:
    """Render the v0.4 research-preview script."""
    defaults_doc = _doc_bullets(m.defaults_applied, empty="  - none")
    limitations = _research_limitations(m)
    limitations_doc = _doc_bullets(limitations)
    stability_doc = _doc_bullets(_research_stability_doc(m))
    material_block = _research_material_block(m)
    boundary_constructor = "Absorber" if m.boundary_type == "absorber" else "PML"
    simulation_options_block = _research_simulation_options_block(m)

    script = f'''\
"""
Auto-generated by optical-spec-agent
Mode: research-preview

This script is not production-grade.
It uses a reference run and structure run.
For nanoparticle-on-film, reference run keeps the film/background and removes the particle.
Scattering is particle-induced relative to the film/background reference, not necessarily
an absolute free-space scattering cross section.

Defaults applied, if any:
{defaults_doc}

Stability diagnostics:
{stability_doc}

Known limitations:
{limitations_doc}
"""

import meep as mp
import numpy as np
import matplotlib.pyplot as plt

import csv
import json

try:
    from scipy.signal import find_peaks
except ImportError:
    find_peaks = None

MODE = "research_preview"
OUTPUT_CSV = "scattering_spectrum.csv"
OUTPUT_FLUX_SURFACES_CSV = "flux_surfaces.csv"
OUTPUT_JSON = "postprocess_results.json"
OUTPUT_PLOT = "scattering_spectrum.png"

particle_material_name = {m.particle_material!r}
film_material_name = {m.film_material!r}
gap_medium_name = {m.gap_medium_name!r}
boundary_type = {m.boundary_type!r}
material_mode = {m.material_mode!r}
diagnostic_profile = {m.diagnostic_profile!r}
source_component_name = {m.source_component!r}
stop_strategy = {m.stop_strategy or ("fixed" if m.diagnostic_profile == "low_cost" else "decay")!r}
flux_mode = {m.flux_mode!r}

defaults_applied = {m.defaults_applied!r}
limitations = {limitations!r}

resolution = {m.resolution}
pml_um = {m.pml_thickness_um:.6f}
boundary_thickness_um = pml_um
wavelength_min_um = {m.wavelength_min_um:.6f}
wavelength_max_um = {m.wavelength_max_um:.6f}
gap_medium_n = {m.gap_medium_n:.6f}
gap_thickness_um = {m.gap_thickness_um:.6f}
r_particle = {m.particle_radius_um:.6f}
film_thickness = {m.film_thickness_um:.6f}
particle_shape = {m.particle_shape!r}

fcen = {(1.0 / ((m.wavelength_min_um + m.wavelength_max_um) / 2.0)):.6f}
df = {(1.0 / m.wavelength_min_um - 1.0 / m.wavelength_max_um):.6f}
nfreq = {m.freq_points}
decay_check_interval = {10 if m.diagnostic_profile == "low_cost" else 50}
decay_threshold = {m.decay_threshold if m.decay_threshold is not None else (1e-3 if m.diagnostic_profile == "low_cost" else 1e-6)}
fixed_run_until = {m.fixed_run_time if m.fixed_run_time is not None else (30 if m.diagnostic_profile == "low_cost" else None)}

simulation_options = {simulation_options_block}
source_component = getattr(mp, source_component_name)


def dielectric_fallback_from_n(n_value: float) -> mp.Medium:
    """Constant-index fallback for dielectric materials only."""
    return mp.Medium(epsilon=n_value ** 2)


{material_block}

# Cell and source geometry
# Keep lateral cell dimensions larger than the two PML layers; otherwise Meep
# can reject the grid with "invalid boundary absorbers for this grid_volume".
vertical_pad = r_particle + 0.6
lateral_pad = pml_um + 0.6
sx = 2 * (r_particle + lateral_pad)
sy = sx
pml_margin = 0.2
interior_sx = sx - 2 * pml_um - 2 * pml_margin
interior_sy = sy - 2 * pml_um - 2 * pml_margin
sz = film_thickness + gap_thickness_um + 2 * r_particle + 2 * vertical_pad + 2 * pml_um
cell = mp.Vector3(sx, sy, sz)

particle_center = mp.Vector3(0, 0, film_thickness + gap_thickness_um + r_particle)
box_center = particle_center
box_size = mp.Vector3(2 * r_particle + 0.12, 2 * r_particle + 0.12, 2 * r_particle + 0.12)
film_bottom_z = 0.0
film_top_z = film_thickness
particle_center_z = float(particle_center.z)
particle_bottom_z = particle_center_z - r_particle
particle_top_z = particle_center_z + r_particle
flux_box_center_z = float(box_center.z)
flux_box_bottom_z = flux_box_center_z - 0.5 * box_size.z
flux_box_top_z = flux_box_center_z + 0.5 * box_size.z
flux_box_intersects_film = flux_box_bottom_z < film_top_z and flux_box_top_z > film_bottom_z
flux_box_intersects_particle = flux_box_bottom_z < particle_top_z and flux_box_top_z > particle_bottom_z
flux_box_encloses_particle = flux_box_bottom_z <= particle_bottom_z and flux_box_top_z >= particle_top_z
geometry_diagnostics = {{
    "film_top_z": film_top_z,
    "particle_center_z": particle_center_z,
    "particle_bottom_z": particle_bottom_z,
    "particle_top_z": particle_top_z,
    "flux_box_center_z": flux_box_center_z,
    "flux_box_bottom_z": flux_box_bottom_z,
    "flux_box_top_z": flux_box_top_z,
    "flux_box_intersects_film": bool(flux_box_intersects_film),
    "flux_box_intersects_particle": bool(flux_box_intersects_particle),
    "flux_box_encloses_particle": bool(flux_box_encloses_particle),
}}
diagnostic_warnings = []
if flux_box_intersects_film:
    diagnostic_warnings.append("flux box intersects film; closed-box flux may be hard to interpret")
if not flux_box_encloses_particle:
    diagnostic_warnings.append("flux box does not fully enclose particle; flux observable may be incomplete")
top_interior_z = 0.5 * sz - boundary_thickness_um - pml_margin
desired_source_z = film_thickness + gap_thickness_um + 2 * r_particle + 0.2
source_z = min(desired_source_z, top_interior_z - 0.05)
source_center = mp.Vector3(0, 0, source_z)


def build_particle():
    if particle_shape == "sphere":
        return mp.Sphere(material=particle_mat, center=particle_center, radius=r_particle)
    if particle_shape == "cube":
        return mp.Block(
            material=particle_mat,
            center=particle_center,
            size=mp.Vector3(2 * r_particle, 2 * r_particle, 2 * r_particle),
        )
    if particle_shape == "cylinder":
        return mp.Cylinder(
            material=particle_mat,
            center=particle_center,
            radius=r_particle,
            height=2 * r_particle,
        )
    raise ValueError(f"Unsupported particle_shape: {{particle_shape}}")


def build_geometry(include_particle: bool) -> list:
    geometry = [
        mp.Block(
            material=film_mat,
            center=mp.Vector3(0, 0, film_thickness / 2.0),
            size=mp.Vector3(interior_sx, interior_sy, film_thickness),
        ),
    ]
    if include_particle:
        geometry.append(build_particle())
    return geometry


def build_sources() -> list:
    return [
        mp.Source(
            src=mp.GaussianSource(fcen, fwidth=df),
            component=source_component,
            center=source_center,
            size=mp.Vector3(interior_sx, interior_sy, 0),
        )
    ]


def build_simulation(include_particle: bool):
    return mp.Simulation(
        cell_size=cell,
        geometry=build_geometry(include_particle=include_particle),
        sources=build_sources(),
        boundary_layers=[mp.{boundary_constructor}(boundary_thickness_um)],
        default_material=gap_medium,
        resolution=resolution,
        **simulation_options,
    )


def make_flux_region_specs(box_center, box_size):
    hx = 0.5 * box_size.x
    hy = 0.5 * box_size.y
    hz = 0.5 * box_size.z
    if flux_mode in ("single_plane", "top_plane"):
        # Diagnostic only: not a closed scattering box or cross-section.
        return [
            (
                "flux_z_plus",
                mp.FluxRegion(
                    center=box_center + mp.Vector3(0, 0, hz),
                    size=mp.Vector3(box_size.x, box_size.y, 0),
                    direction=mp.Z,
                    weight=1.0,
                ),
            )
        ]
    return [
        (
            "flux_x_minus",
            mp.FluxRegion(
                center=box_center + mp.Vector3(-hx, 0, 0),
                size=mp.Vector3(0, box_size.y, box_size.z),
                direction=mp.X,
                weight=-1.0,
            ),
        ),
        (
            "flux_x_plus",
            mp.FluxRegion(
                center=box_center + mp.Vector3(hx, 0, 0),
                size=mp.Vector3(0, box_size.y, box_size.z),
                direction=mp.X,
                weight=1.0,
            ),
        ),
        (
            "flux_y_minus",
            mp.FluxRegion(
                center=box_center + mp.Vector3(0, -hy, 0),
                size=mp.Vector3(box_size.x, 0, box_size.z),
                direction=mp.Y,
                weight=-1.0,
            ),
        ),
        (
            "flux_y_plus",
            mp.FluxRegion(
                center=box_center + mp.Vector3(0, hy, 0),
                size=mp.Vector3(box_size.x, 0, box_size.z),
                direction=mp.Y,
                weight=1.0,
            ),
        ),
        (
            "flux_z_minus",
            mp.FluxRegion(
                center=box_center + mp.Vector3(0, 0, -hz),
                size=mp.Vector3(box_size.x, box_size.y, 0),
                direction=mp.Z,
                weight=-1.0,
            ),
        ),
        (
            "flux_z_plus",
            mp.FluxRegion(
                center=box_center + mp.Vector3(0, 0, hz),
                size=mp.Vector3(box_size.x, box_size.y, 0),
                direction=mp.Z,
                weight=1.0,
            ),
        ),
    ]


def make_flux_regions(box_center, box_size):
    return [region for _name, region in make_flux_region_specs(box_center, box_size)]


def flux_surface_names():
    return [name for name, _region in make_flux_region_specs(box_center, box_size)]


def add_closed_box_flux(sim):
    return [
        sim.add_flux(fcen, df, nfreq, region)
        for region in make_flux_regions(box_center, box_size)
    ]


def run_reference():
    sim_ref = build_simulation(include_particle=False)
    flux_ref = add_closed_box_flux(sim_ref)
    if stop_strategy == "fixed":
        # Diagnostic/probe fixed run: bounded, not necessarily physically converged.
        sim_ref.run(until=fixed_run_until)
    else:
        sim_ref.run(
            until_after_sources=mp.stop_when_fields_decayed(
                decay_check_interval, mp.Ez, box_center, decay_threshold
            )
        )
    ref_flux_data = [sim_ref.get_flux_data(flux_obj) for flux_obj in flux_ref]
    freqs = mp.get_flux_freqs(flux_ref[0])
    sim_ref.reset_meep()
    return freqs, ref_flux_data


def run_structure(ref_flux_data):
    sim_scat = build_simulation(include_particle=True)
    flux_scat = add_closed_box_flux(sim_scat)
    for flux_obj, flux_data in zip(flux_scat, ref_flux_data):
        sim_scat.load_minus_flux_data(flux_obj, flux_data)
    if stop_strategy == "fixed":
        # Diagnostic/probe fixed run: bounded, not necessarily physically converged.
        sim_scat.run(until=fixed_run_until)
    else:
        sim_scat.run(
            until_after_sources=mp.stop_when_fields_decayed(
                decay_check_interval, mp.Ez, box_center, decay_threshold
            )
        )
    freqs = mp.get_flux_freqs(flux_scat[0])
    surface_fluxes = [np.array(mp.get_fluxes(flux_obj)) for flux_obj in flux_scat]
    particle_induced_flux_relative = np.sum(surface_fluxes, axis=0)
    sim_scat.reset_meep()
    return freqs, particle_induced_flux_relative, flux_surface_names(), surface_fluxes


def write_csv(wavelength_nm, particle_induced_flux_relative):
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["wavelength_nm", "particle_induced_flux_relative"])
        for wavelength_nm_value, flux_value in zip(wavelength_nm, particle_induced_flux_relative):
            writer.writerow([float(wavelength_nm_value), float(flux_value)])


def write_flux_surfaces_csv(wavelength_nm, surface_names, surface_fluxes, flux_total):
    canonical_names = [
        "flux_x_minus",
        "flux_x_plus",
        "flux_y_minus",
        "flux_y_plus",
        "flux_z_minus",
        "flux_z_plus",
    ]
    surface_lookup = {{
        name: np.asarray(values, dtype=float)
        for name, values in zip(surface_names, surface_fluxes)
    }}
    with open(OUTPUT_FLUX_SURFACES_CSV, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["wavelength_nm", *canonical_names, "flux_total"])
        for idx, wavelength_nm_value in enumerate(wavelength_nm):
            row = [float(wavelength_nm_value)]
            for name in canonical_names:
                values = surface_lookup.get(name)
                row.append(float(values[idx]) if values is not None else "")
            row.append(float(flux_total[idx]))
            writer.writerow(row)


def save_plot(wavelength_nm, particle_induced_flux_relative):
    plt.figure(figsize=(8, 5))
    plt.plot(wavelength_nm, particle_induced_flux_relative, "b-")
    plt.xlabel("Wavelength (nm)")
    plt.ylabel("Particle-induced flux (arb. units)")
    plt.title(
        f"Research-preview scattering response — {{particle_material_name}} "
        f"{{particle_shape}} on {{film_material_name}} film"
    )
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(OUTPUT_PLOT, dpi=150)
    plt.close()


def estimate_resonance_and_fwhm(wavelength_nm, flux_values):
    flux_array = np.asarray(flux_values, dtype=float)
    if flux_array.size < 3:
        return None, None

    peak_indices = []
    if find_peaks is not None:
        peaks, _props = find_peaks(flux_array)
        peak_indices = [int(idx) for idx in peaks]

    if not peak_indices:
        best_idx = int(np.argmax(flux_array))
        if 0 < best_idx < flux_array.size - 1:
            if flux_array[best_idx] > flux_array[best_idx - 1] and flux_array[best_idx] >= flux_array[best_idx + 1]:
                peak_indices = [best_idx]

    if not peak_indices:
        return None, None

    peak_idx = max(peak_indices, key=lambda idx: flux_array[idx])
    peak_flux = float(flux_array[peak_idx])
    if not np.isfinite(peak_flux):
        return None, None

    resonance_wavelength_nm = float(wavelength_nm[peak_idx])
    if peak_flux <= 0:
        return resonance_wavelength_nm, None

    half_max = peak_flux / 2.0
    left_candidates = np.where(flux_array[:peak_idx] <= half_max)[0]
    right_candidates = np.where(flux_array[peak_idx:] <= half_max)[0]

    if left_candidates.size == 0 or right_candidates.size == 0:
        return resonance_wavelength_nm, None

    left_idx = int(left_candidates[-1])
    right_idx = int(peak_idx + right_candidates[0])
    if right_idx <= left_idx:
        return resonance_wavelength_nm, None

    fwhm_nm = float(abs(wavelength_nm[right_idx] - wavelength_nm[left_idx]))
    return resonance_wavelength_nm, fwhm_nm


def write_results_json(resonance_wavelength_nm, fwhm_nm):
    results = {{
        "mode": MODE,
        "diagnostic_profile": diagnostic_profile,
        "boundary_type": boundary_type,
        "material_mode": material_mode,
        "source_component": source_component_name,
        "stop_strategy": stop_strategy,
        "fixed_run_time": fixed_run_until,
        "decay_threshold": decay_threshold,
        "flux_mode": flux_mode,
        "resolution": resolution,
        "freq_points": nfreq,
        "particle_material": particle_material_name,
        "film_material": film_material_name,
        "gap_medium_name": gap_medium_name,
        "gap_medium_n": gap_medium_n,
        "gap_thickness_nm": gap_thickness_um * 1000.0,
        "wavelength_min_nm": wavelength_min_um * 1000.0,
        "wavelength_max_nm": wavelength_max_um * 1000.0,
        "resonance_wavelength_nm": resonance_wavelength_nm,
        "fwhm_nm": fwhm_nm,
        "defaults_applied": defaults_applied,
        "limitations": limitations,
        "warnings": diagnostic_warnings,
        "geometry_diagnostics": geometry_diagnostics,
    }}
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)


def main():
    _freqs_ref, ref_flux_data = run_reference()
    freqs_scat, particle_induced_flux_relative, surface_names, surface_fluxes = run_structure(ref_flux_data)

    freqs_scat = np.asarray(freqs_scat, dtype=float)
    wavelength_nm = 1000.0 / freqs_scat

    write_csv(wavelength_nm, particle_induced_flux_relative)
    write_flux_surfaces_csv(wavelength_nm, surface_names, surface_fluxes, particle_induced_flux_relative)
    save_plot(wavelength_nm, particle_induced_flux_relative)

    resonance_wavelength_nm, fwhm_nm = estimate_resonance_and_fwhm(
        wavelength_nm, particle_induced_flux_relative
    )
    write_results_json(resonance_wavelength_nm, fwhm_nm)

    print(f"Saved {{OUTPUT_CSV}}")
    print(f"Saved {{OUTPUT_FLUX_SURFACES_CSV}}")
    print(f"Saved {{OUTPUT_JSON}}")
    print(f"Saved {{OUTPUT_PLOT}}")
    if resonance_wavelength_nm is not None:
        print(f"Resonance wavelength: {{resonance_wavelength_nm:.2f}} nm")
    else:
        print("Resonance wavelength: null")
    if fwhm_nm is not None:
        print(f"FWHM: {{fwhm_nm:.2f}} nm")
    else:
        print("FWHM: null")


if __name__ == "__main__":
    main()
'''
    return script


def _render_smoke(m: MeepInputModel) -> str:
    """Minimal Meep script for smoke validation.

    Uses simple dielectric materials, ultra-low resolution, few time steps.
    NOT physically meaningful — only verifies the generated script structure
    can be instantiated and stepped by Meep without errors.
    """
    particle_geom_map = {
        "sphere": (
            "mp.Sphere(material=particle_mat,\n"
            "          center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            "          radius=r_particle)"
        ),
        "cube": (
            "mp.Block(material=particle_mat,\n"
            "         center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            "         size=mp.Vector3(2*r_particle, 2*r_particle, 2*r_particle))"
        ),
        "cylinder": (
            "mp.Cylinder(material=particle_mat,\n"
            "             center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            "             radius=r_particle, height=2*r_particle)"
        ),
    }
    particle_geom = particle_geom_map.get(m.particle_shape, particle_geom_map["sphere"])

    return f'''\
"""Meep SMOKE test — auto-generated by optical-spec-agent.
NOT for production. Verifies script structure only.
"""
import meep as mp
import numpy as np

# Simple dielectric materials (no dispersion)
particle_mat = mp.Medium(epsilon=1.0)
film_mat = mp.Medium(epsilon=1.0)
gap_medium = mp.Medium(epsilon={m.gap_medium_n ** 2:.4f})

resolution = 10
pml_um = 0.5
fcen = {(1.0 / ((m.wavelength_min_um + m.wavelength_max_um) / 2.0)):.4f}
df = {(1.0 / m.wavelength_min_um - 1.0 / m.wavelength_max_um):.4f}
nfreq = 3

r_particle = {m.particle_radius_um:.6f}
film_thickness = {m.film_thickness_um:.6f}
gap = {m.gap_thickness_um:.6f}

pad = 1.0  # generous fixed padding so cell >> PML
sx = 2 * pad
sy = sx
sz = film_thickness + gap + 2 * r_particle + 2 * pad + 2 * pml_um
cell = mp.Vector3(sx, sy, sz)

geometry = [
    mp.Block(material=film_mat,
             center=mp.Vector3(0, 0, film_thickness / 2),
             size=mp.Vector3(mp.inf, mp.inf, film_thickness)),
    {particle_geom},
]

sources = [mp.Source(
    src=mp.GaussianSource(fcen, fwidth=df),
    component=mp.Ez,
    center=mp.Vector3(0, 0, film_thickness + 2 * r_particle + pml_um + 0.3),
    size=mp.Vector3(sx, sy),
)]

sim = mp.Simulation(
    cell_size=cell,
    geometry=geometry,
    sources=sources,
    boundary_layers=[mp.PML(pml_um)],
    default_material=gap_medium,
    resolution=resolution,
)

flux_box = sim.add_flux(
    fcen, df, nfreq,
    mp.FluxRegion(center=mp.Vector3(0, 0, film_thickness + gap + 2 * r_particle + 0.02),
                  size=mp.Vector3(2*r_particle + 0.05, 2*r_particle + 0.05, 0)),
)

sim.run(until=20)

freqs = mp.get_flux_freqs(flux_box)
flux = mp.get_fluxes(flux_box)
assert len(freqs) == nfreq
assert len(flux) == nfreq

print("SMOKE TEST PASSED")
'''


def _preview_material_defs(m: MeepInputModel) -> str:
    """Generate simplified Drude material definitions for preview mode."""
    defs = []
    for label, mat in [("particle_mat", m.particle_material), ("film_mat", m.film_material)]:
        if mat in ("Au", "au"):
            defs.append(
                f'# Simplified Drude model for Au (placeholder for Johnson-Christy data)\n'
                f'{label} = mp.Drude(epsilon=1.0, plasma_freq=1.37e16, gamma=4.08e13)\n'
                f'# In Meep units: ω_p = 9.03 eV, γ = 0.071 eV → converted to 1/μm\n'
                f'# For production: use mp.Medium(epsilon=...) with tabulated n(ω), k(ω)'
            )
        elif mat in ("Ag", "ag"):
            defs.append(
                f'# Simplified Drude model for Ag (placeholder)\n'
                f'{label} = mp.Drude(epsilon=1.0, plasma_freq=1.37e16, gamma=2.73e13)\n'
                f'# For production: use full Lorentz-Drude or tabulated data'
            )
        else:
            defs.append(f'{label} = mp.Medium(epsilon=1.0)  # placeholder for {mat}')
    return "\n".join(defs)


def _preview_geometry_block(m: MeepInputModel) -> str:
    """Generate geometry and cell setup code for preview mode."""
    if m.particle_shape == "sphere":
        particle_geom = (
            "mp.Sphere(material=particle_mat,\n"
            "           center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            "           radius=r_particle)"
        )
    elif m.particle_shape == "cube":
        particle_geom = (
            "mp.Block(material=particle_mat,\n"
            "         center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            "         size=mp.Vector3(2*r_particle, 2*r_particle, 2*r_particle))"
        )
    elif m.particle_shape == "cylinder":
        particle_geom = (
            "mp.Cylinder(material=particle_mat,\n"
            "             center=mp.Vector3(0, 0, film_thickness + gap + r_particle),\n"
            "             radius=r_particle, height=2*r_particle)"
        )
    else:
        particle_geom = "mp.Sphere(material=particle_mat, center=mp.Vector3(0, 0, film_thickness + gap + r_particle), radius=r_particle)  # fallback"

    return f'''\
r_particle = {m.particle_radius_um:.6f}   # particle radius (μm) — from spec.particle_info
film_thickness = {m.film_thickness_um:.6f}  # film thickness (μm) — from spec.substrate_or_film_info
gap = {m.gap_thickness_um:.6f}              # gap thickness (μm) — from spec.gap_medium

# Cell size: padding around the structure
pad = r_particle + 0.5  # μm padding
sx = 2 * (r_particle + pad)
sy = sx
sz = film_thickness + gap + 2 * r_particle + 2 * pad + 2 * pml_um
cell = mp.Vector3(sx, sy, sz)

geometry = [
    # Film layer (extends in x-y)
    mp.Block(material=film_mat,
             center=mp.Vector3(0, 0, film_thickness / 2),
             size=mp.Vector3(mp.inf, mp.inf, film_thickness)),
    # Particle on top of film
    {particle_geom},
]'''


def _preview_sweep_loop(m: MeepInputModel) -> tuple[str, str]:
    """Return (loop_header, loop_footer) for a preview gap sweep."""
    steps = m.sweep_steps or 11
    return (
        f'gap_values = np.linspace({m.sweep_start_um:.6f}, {m.sweep_end_um:.6f}, {steps})\n'
        f'print(f"Sweeping gap from {{gap_values[0]*1000:.1f}} to {{gap_values[-1]*1000:.1f}} nm in {{len(gap_values)}} steps")\n'
        f'all_flux = []\n'
        f'for i, g in enumerate(gap_values):\n'
        f'    print(f"  Step {{i+1}}/{{len(gap_values)}}: gap = {{g*1000:.1f}} nm")\n'
        f'    gap = g\n'
        f'    # Rebuild geometry with new gap\n'
        f'    geometry = [\n'
        f'        mp.Block(material=film_mat, center=mp.Vector3(0, 0, film_thickness / 2), size=mp.Vector3(mp.inf, mp.inf, film_thickness)),\n'
        f'        mp.Sphere(material=particle_mat, center=mp.Vector3(0, 0, film_thickness + gap + r_particle), radius=r_particle),\n'
        f'    ]\n'
        f'    sim = mp.Simulation(cell_size=cell, geometry=geometry, sources=sources, boundary_layers=[mp.PML(pml_um)], default_material=gap_medium, resolution=resolution)\n'
        f'    flux_box = sim.add_flux(fcen, df, nfreq, mp.FluxRegion(center=mp.Vector3(0, 0, film_thickness + gap + r_particle + r_particle + 0.05), size=mp.Vector3(2*r_particle + 0.1, 2*r_particle + 0.1, 0)))\n',
        f'    all_flux.append(mp.get_fluxes(flux_box))\n'
        f'    sim.reset()\n'
        f'\n'
        f'flux = np.mean(all_flux, axis=0)  # simplified: average over sweep points'
    )


def _preview_postprocess_block(m: MeepInputModel) -> str:
    """Generate post-processing code for preview resonance/FWHM extraction."""
    if not m.postprocess:
        return ""

    lines = ["# =====================================================================",
             "# Post-processing: resonance / FWHM extraction",
             "# ====================================================================="]

    if "resonance_wavelength" in m.postprocess:
        lines.append("""
# Find resonance peak
peaks, props = find_peaks(flux, height=max(flux) * 0.5)
if len(peaks) > 0:
    res_idx = peaks[np.argmax(props["peak_heights"])]
    res_wl = wl_nm[res_idx]
    print(f"Resonance wavelength: {res_wl:.1f} nm")
else:
    print("No clear resonance peak found")
""")

    if "fwhm_extraction" in m.postprocess:
        lines.append("""
# FWHM estimation (simplified half-max method)
if len(peaks) > 0:
    peak_flux = max(flux)
    half_max = peak_flux / 2.0
    above = np.where(np.array(flux) >= half_max)[0]
    if len(above) > 1:
        fwhm = wl_nm[above[-1]] - wl_nm[above[0]]
        print(f"FWHM: {fwhm:.1f} nm")
    else:
        print("Could not estimate FWHM")
""")

    if "T2_extraction" in m.postprocess:
        lines.append("""
# T2 (dephasing time) from FWHM: T2 = 2ℏ / Γ, where Γ = ℏω·FWHM/λ²
# Simplified: T2 ≈ 2λ² / (2πc·FWHM)
if len(peaks) > 0 and len(above) > 1:
    import scipy.constants as const
    res_wl_m = res_wl * 1e-9
    fwhm_m = fwhm * 1e-9
    T2 = 2 * res_wl_m**2 / (2 * np.pi * const.c * fwhm_m)
    print(f"T2 (dephasing time): {T2*1e15:.1f} fs")
""")

    return "\n".join(lines)


def _doc_bullets(items: list[str], *, empty: str = "  - none") -> str:
    if not items:
        return empty
    return "\n".join(f"  - {item}" for item in items)


def _research_stability_doc(m: MeepInputModel) -> list[str]:
    """Describe research-preview stability diagnostics in the generated header."""
    courant_note = "Meep default" if m.courant is None else str(m.courant)
    eps_note = "Meep default" if m.eps_averaging is None else str(m.eps_averaging)
    notes = [
        f"diagnostic_profile={m.diagnostic_profile}",
        f"boundary_type={m.boundary_type}",
        f"material_mode={m.material_mode}",
        f"source_component={m.source_component}",
        f"stop_strategy={m.stop_strategy or ('fixed' if m.diagnostic_profile == 'low_cost' else 'decay')}",
        f"flux_mode={m.flux_mode}",
        f"resolution={m.resolution}",
        f"freq_points={m.freq_points}",
        f"Courant={courant_note}",
        f"eps_averaging={eps_note}",
    ]
    if m.diagnostic_profile == "low_cost":
        notes.append("low_cost uses a fixed short run and relaxed settings; results are diagnostic only.")
        notes.append("low_cost output is nonphysical and not valid for physical interpretation.")
    if m.boundary_type == "absorber":
        notes.append("Absorber boundary is a diagnostic workaround for possible PML/dispersive-material blow-up.")
    if m.material_mode == "dielectric_sanity":
        notes.append("material_mode=dielectric_sanity is nonphysical and only validates execution pipeline.")
    if m.material_mode in ("particle_library_film_dielectric", "particle_dielectric_film_library"):
        notes.append(f"material_mode={m.material_mode} is a mixed-material isolation probe, not a validated physical setup.")
    if m.flux_mode == "single_plane":
        notes.append("flux_mode=single_plane is diagnostic only and not a scattering cross-section.")
    if m.flux_mode == "top_plane":
        notes.append("flux_mode=top_plane measures a diagnostic upward plane flux only; it is not a closed scattering cross-section.")
    return notes


def _research_material_block(m: MeepInputModel) -> str:
    """Render research-preview material resolution code."""
    if m.material_mode == "dielectric_sanity":
        return """\
# material_mode=dielectric_sanity is deliberately nonphysical.
# It replaces metal dispersion with constant dielectric placeholders to validate
# reference/structure/flux subtraction and CSV/JSON output plumbing.
particle_mat = mp.Medium(epsilon=2.25)
film_mat = mp.Medium(epsilon=2.25)
gap_medium = dielectric_fallback_from_n(gap_medium_n)
"""

    if m.material_mode == "particle_library_film_dielectric":
        return """\
try:
    from meep.materials import Au, Ag, SiO2, Si3N4, Al2O3
except ImportError:
    Au = Ag = SiO2 = Si3N4 = Al2O3 = None


def resolve_metal(name: str):
    library = {"Au": Au, "Ag": Ag}
    material = library.get(name)
    if material is None:
        raise RuntimeError(
            f"research-preview requires meep.materials.{name} for dispersive metals; "
            "no placeholder metal fallback is provided."
        )
    return material


def resolve_gap_medium(name: str, fallback_n: float):
    library = {"SiO2": SiO2, "Si3N4": Si3N4, "Al2O3": Al2O3}
    material = library.get(name)
    if material is not None:
        return material
    return dielectric_fallback_from_n(fallback_n)


# Mixed-material isolation probe: library particle, dielectric placeholder film.
particle_mat = resolve_metal(particle_material_name)
film_mat = mp.Medium(epsilon=2.25)
gap_medium = resolve_gap_medium(gap_medium_name, gap_medium_n)
"""

    if m.material_mode == "particle_dielectric_film_library":
        return """\
try:
    from meep.materials import Au, Ag, SiO2, Si3N4, Al2O3
except ImportError:
    Au = Ag = SiO2 = Si3N4 = Al2O3 = None


def resolve_metal(name: str):
    library = {"Au": Au, "Ag": Ag}
    material = library.get(name)
    if material is None:
        raise RuntimeError(
            f"research-preview requires meep.materials.{name} for dispersive metals; "
            "no placeholder metal fallback is provided."
        )
    return material


def resolve_gap_medium(name: str, fallback_n: float):
    library = {"SiO2": SiO2, "Si3N4": Si3N4, "Al2O3": Al2O3}
    material = library.get(name)
    if material is not None:
        return material
    return dielectric_fallback_from_n(fallback_n)


# Mixed-material isolation probe: dielectric placeholder particle, library film.
particle_mat = mp.Medium(epsilon=2.25)
film_mat = resolve_metal(film_material_name)
gap_medium = resolve_gap_medium(gap_medium_name, gap_medium_n)
"""

    return """\
try:
    from meep.materials import Au, Ag, SiO2, Si3N4, Al2O3
except ImportError:
    Au = Ag = SiO2 = Si3N4 = Al2O3 = None


def resolve_metal(name: str):
    library = {"Au": Au, "Ag": Ag}
    material = library.get(name)
    if material is None:
        raise RuntimeError(
            f"research-preview requires meep.materials.{name} for dispersive metals; "
            "no placeholder metal fallback is provided."
        )
    return material


def resolve_gap_medium(name: str, fallback_n: float):
    library = {"SiO2": SiO2, "Si3N4": Si3N4, "Al2O3": Al2O3}
    material = library.get(name)
    if material is not None:
        return material
    # Fallback only for dielectric/background media when the library material is unavailable.
    return dielectric_fallback_from_n(fallback_n)


particle_mat = resolve_metal(particle_material_name)
film_mat = resolve_metal(film_material_name)
gap_medium = resolve_gap_medium(gap_medium_name, gap_medium_n)
"""


def _research_simulation_options_block(m: MeepInputModel) -> str:
    """Render optional mp.Simulation kwargs for research-preview diagnostics."""
    lines = ["{"]
    if m.courant is not None:
        lines.append(f'    "Courant": {m.courant!r},')
    if m.eps_averaging is not None:
        lines.append(f'    "eps_averaging": {m.eps_averaging!r},')
    lines.append("}")
    return "\n".join(lines)


def _research_limitations(m: MeepInputModel) -> list[str]:
    limitations = [
        "Research-preview only; not production-grade or publication-ready.",
        "Uses particle-induced flux relative to a film/background reference run.",
        "Peak extraction is heuristic and may return null when no clear resonance is detected.",
        "Gap/background fallback may use a constant-index mp.Medium(epsilon=n**2).",
    ]
    if m.boundary_type == "pml" and m.material_mode == "library":
        limitations.append(
            "PML with dispersive library metals may be numerically unstable in some Meep setups."
        )
    if m.boundary_type == "absorber":
        limitations.append(
            "Absorber boundary is a stability diagnostic workaround and may change quantitative results."
        )
    if m.material_mode == "dielectric_sanity":
        limitations.append(
            "Dielectric sanity material mode is nonphysical and should not be interpreted as a metal scattering result."
        )
    if m.material_mode in ("particle_library_film_dielectric", "particle_dielectric_film_library"):
        limitations.append(
            f"{m.material_mode} is a mixed-material stability isolation probe and is not a validated physical model."
        )
    if m.diagnostic_profile == "low_cost":
        limitations.append(
            "diagnostic_profile=low_cost uses low resolution, few frequency points, and fixed short runs; it validates execution plumbing only."
        )
    if m.diagnostic_profile == "physical_probe":
        limitations.append(
            "diagnostic_profile=physical_probe is a v0.6 pre-study setting, not production validation."
        )
    if m.flux_mode == "single_plane":
        limitations.append(
            "flux_mode=single_plane is diagnostic only and not a scattering cross-section."
        )
    if m.flux_mode == "top_plane":
        limitations.append(
            "top_plane flux is diagnostic only and not a closed scattering cross-section."
        )
    if m.sweep_variable:
        limitations.append(
            "If the input spec contains a sweep, this research-preview script renders a single nominal geometry rather than a full automated sweep pipeline."
        )
    return limitations
