"""
Meep FDTD simulation — auto-generated by optical-spec-agent (Meep adapter v0.1).

Physical system: nanoparticle_on_film
  particle: Au sphere, radius=40.0nm
  film:     Au, thickness=100.0nm
  gap:      n=1.45, thickness=5.0nm
  source:   plane wave, 400-900nm

NOTE: Material model is SIMPLIFIED (single-Drude). For production use, replace
      with full Johnson-Christy or Lorentz-Drude fit data.
"""

import meep as mp
import numpy as np
import matplotlib.pyplot as plt


# =====================================================================
# Materials (simplified single-Drude model)
# =====================================================================
# Simplified Drude model for Au (placeholder for Johnson-Christy data)
particle_mat = mp.Drude(epsilon=1.0, plasma_freq=1.37e16, gamma=4.08e13)
# In Meep units: ω_p = 9.03 eV, γ = 0.071 eV → converted to 1/μm
# For production: use mp.Medium(epsilon=...) with tabulated n(ω), k(ω)
# Simplified Drude model for Au (placeholder for Johnson-Christy data)
film_mat = mp.Drude(epsilon=1.0, plasma_freq=1.37e16, gamma=4.08e13)
# In Meep units: ω_p = 9.03 eV, γ = 0.071 eV → converted to 1/μm
# For production: use mp.Medium(epsilon=...) with tabulated n(ω), k(ω)
gap_medium = mp.Medium(epsilon=2.1025)

# =====================================================================
# Simulation parameters
# =====================================================================
resolution = 50  # pixels/μm
pml_um = 1.0
fcen = 1.5385  # center frequency (1/μm)
df = 1.3889  # frequency width (1/μm)
nfreq = 200

# =====================================================================
# Geometry & cell
# =====================================================================
r_particle = 0.040000   # particle radius (μm) — from spec.particle_info
film_thickness = 0.100000  # film thickness (μm) — from spec.substrate_or_film_info
gap = 0.005000              # gap thickness (μm) — from spec.gap_medium

# Cell size: padding around the structure
pad = r_particle + 0.5  # μm padding
sx = 2 * (r_particle + pad)
sy = sx
sz = film_thickness + gap + 2 * r_particle + 2 * pad + 2 * pml_um
cell = mp.Vector3(sx, sy, sz)

geometry = [
    # Film layer (extends in x-y)
    mp.Block(material=film_mat,
             center=mp.Vector3(0, 0, film_thickness / 2),
             size=mp.Vector3(mp.inf, mp.inf, film_thickness)),
    # Particle on top of film
    mp.Sphere(material=particle_mat,
           center=mp.Vector3(0, 0, film_thickness + gap + r_particle),
           radius=r_particle),
]

# =====================================================================
# Source: plane wave
# =====================================================================
sources = [mp.Source(
    src=mp.GaussianSource(fcen, fwidth=df),
    component=mp.Ez,
    center=mp.Vector3(0, 0, 1.68),
    size=mp.Vector3(sx, sy),
)]

# =====================================================================
# Simulation
# =====================================================================
sim = mp.Simulation(
    cell_size=cell,
    geometry=geometry,
    sources=sources,
    boundary_layers=[mp.PML(pml_um)],
    default_material=gap_medium,
    resolution=resolution,
)

# Flux monitor boxes for scattering cross-section
# (simplified: one box around the particle)
box_zcen = film_thickness + gap + r_particle
flux_box = sim.add_flux(
    fcen, df, nfreq,
    mp.FluxRegion(center=mp.Vector3(0, 0, box_zcen + r_particle + 0.05), size=mp.Vector3(2*r_particle + 0.1, 2*r_particle + 0.1, 0)),
)


sim.run(until=200)  # simplified: fixed time steps. Adjust based on your needs.


# =====================================================================
# Post-processing: spectrum
# =====================================================================
freqs = mp.get_flux_freqs(flux_box)
flux = mp.get_fluxes(flux_box)
wl_um = np.array(1.0 / np.array(freqs))  # wavelength in μm
wl_nm = wl_um * 1000

plt.figure(figsize=(8, 5))
plt.plot(wl_nm, flux, "b-")
plt.xlabel("Wavelength (nm)")
plt.ylabel("Flux (arb. units)")
plt.title("Scattering flux — Au sphere on Au film")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("scattering_spectrum.png", dpi=150)
plt.show()
print("Spectrum saved to scattering_spectrum.png")


